version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myems-api
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: myems-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
